version: '3.2'

services:
  # Express App
  app:
    build: .
    volumes:
      - ./:/express-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=express_app
      - DB_USER=root
      - DB_PASS=dev-password

  # MySQL Database
  db:
    image: mariadb:10.4
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=dev-password
      - MYSQL_DATABASE=express_app
    volumes:
      - rest-express-data:/var/lib/mysql

volumes:
  rest-express-data: